Repository Dev-FE-1/Toy_Project_II_team4, pull requests merged in 2024-08, with the labels that each got.

#68 Fix : navLinks 파일명 수정
  src/components/nav/NavLinks.tsx
Labels: 🐞 BugFix

#73 Dialog 컴포넌트 추가
  src/components/datepicker/DatePicker.tsx
  src/components/modal/BasicDialog.tsx
  src/pages/salaryAdjustment/Cate1.tsx
  src/pages/salaryAdjustment/Cate2.tsx
  src/pages/salaryAdjustment/Cate3.tsx
  src/pages/salaryAdjustment/Cate4.tsx
  src/pages/salaryAdjustment/FormWrap.tsx
  src/pages/salaryAdjustment/SalaryAdjustment.style.ts
  src/pages/salaryAdjustment/SalaryAdjustment.tsx
Labels: ✨ Feature

#70 Feature: 급여명세서 pdf 다운로드 기능 구현
  src/pages/salaryDetail/SalaryDetail.style.ts
  src/pages/salaryDetail/SalaryDetail.tsx
Labels: ✨ Feature

#79 Feat : 급여명세서 월별 조회 버튼 수정
  package-lock.json
  package.json
  src/pages/salaryDetail/MoveMonth.tsx
  src/pages/salaryDetail/SalaryDetail.tsx
Labels: ✨ Feature

#85 Fix : globalstyle.tsx 수정
  src/styles/GlobalStyle.tsx
Labels: 🎨 DesignUI

#106 [Feature] 급여명세서 내 정정버튼 동작 수정
  src/pages/salaryDetail/DetailMonthModal.tsx
  src/pages/salaryDetail/SalaryDetailPage.tsx
Labels: ✨ Feature

#115 [Fix/modal] 모바일에서 모달 꽉차게 수정
  src/components/modal/BasicModal.tsx
Labels: 🎨 DesignUI

#128 design : 정정내역 페이지 아코디언 UI 수정
  src/pages/salaryAdjustment/AccordionList.tsx
  src/pages/salaryAdjustment/SalaryAdjustment.style.ts
Labels: 🎨 DesignUI
